baseURL = 'http://fatties-blog.vercel.app'
languageCode = 'en-us'
title = 'Fatima`s Blog'
theme = 'neopost'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      admonition = true

[params]
  theme        = "light-pink"
  favicon      = "/favicon.ico"
  customCss = [
    "css/custom.css",
  ]

  [params.read_more]
    length_limit = 120
    [params.read_more.text]
      more = "read more"
      less = "read less"

  posts_per_page = 1

[module]
  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"

[markup.highlight]
  noClasses = true
  style     = "monokailight"
  